pipeline:
  test:
    image: webdevops/php:${PHP_VERSION}
    commands:
      - composer install
      - composer test

matrix:
  PHP_VERSION:
  - "ubuntu-12.04" # 5.3
  - "ubuntu-15.04" # 5.6
  - "ubuntu-16.04" # 7.0
