pipeline:
  test:
    image: webdevops/php:${PHP_VERSION}
    commands:
      - php -v
      - sleep 3
      - composer install
      - composer test

matrix:
  PHP_VERSION:
  - "ubuntu-12.04" # 5.3
  - "ubuntu-15.04" # 5.6
  - "ubuntu-16.04" # 7.0

services:
  fakeserver:
    image: vimagick/json-server
    command: ["https://raw.githubusercontent.com/vimagick/dockerfiles/master/json-server/db.json"]
